name: Publish

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

env:
  logo: https://github.com/FNNDSC/cube-design/blob/master/_common-assets/ChRISlogo-color.svg.png?raw=true

jobs:
  pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        # https://github.com/snok/install-poetry#caching-the-poetry-installation
      - name: Load cached poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-0  # increment to reset cache
      - name: Install Python Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: jennydaman/install-poetry@83b32fe109e39af733e68ef8544a6f665c470a16
        with:
          version: '1.3.1'

      - name: Install
        run: poetry install
      - name: Publish
        run: poetry publish --build --username='__token__' --password='${{ secrets.PYPI_API_TOKEN }}'


      - name: Deploy docs (version)
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: pdoc
          clean: true
          clean-exclude: 'v*.*.*/'
          target-folder: "${{ github.ref_name }}"
      - name: Deploy docs (latest)
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: pdoc
          clean: false
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          body: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_name }}"
